### PR TITLE
202310 Query API

### PR DESCRIPTION
**Pull request by petermarshallio**
New notebook going into how to form a request to the Druid SQL API

### CODE REVIEW

**Comment by petermarshallio** [comment]
During creation, reported an issue in the way that CAST works. @gianm was able to clarify:

> Some functions have overly-aggressive validation that some arg must be literal, and won't accept casted literals
> in general we want any function that accepts a literal to also be able to accept a casted literal
> often there's two different implementations, one for a literal and one for a nonliteral parameter,
> since we can often do optimized code for literals (for time_in_interval the optimized code parses
> the interval just once per query, instead of once-per-row)
> sometimes if we think people aren't in practice going to want to use anything other than a
> literal ... [Druid] only implements the optimized literal code path and we require the parameter be a literal
> we now recommend people always CAST(? AS type), but not all functions accept casted literals,
> so people can't actually implement our recommendation in all cases. The fix would be to update
> validations for various functions to accept casted literals as well.
> I believe this means finding all usages of Calcite's builtin OperandTypes.LITERAL

From this the following functions need to be avoided in this notebook for now:

* TIME_IN_INTERVAL
* JSON_KEYS
* EARLIEST and LATEST (for maxBytesPerString)
* COMPLEX_DECODE_BASE64 (for typeName)
* APPROX_QUANTILE
* APPROX_QUANTILE_FIXED_BUCKETS
* BLOOM_FILTER
* TDIGEST_QUANTILE
* TDIGEST_GENERATE_SKETCH

**Review by sergioferragut — APPROVED** [review]
I don't have any change requests for this one.
You could improve the output of the last cell, like you did in the others, with 
```
print(json.dumps(dict(query_result.headers), indent=2))
```

**Review by sergioferragut — APPROVED** [review]
I don't have any change requests for this one.
You could improve the output of the last cell, like you did in the others, with 
```
print(json.dumps(dict(query_result.headers), indent=2))
```

**Comment by petermarshallio** [comment]
Thank you @sergioferragut ! :) Merged.

**Pull request merged**
